---
apiVersion: v1
kind: Secret
metadata:
  name: idgenerator-lt-spring
type: Opaque
stringData:
  user: SPRING.SECURITY.USER.NAME
  password: SPRING.SECURITY.USER.PASSWORD
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: idgenerator-lt-metrics
spec:
  endpoints:
    - interval: 15s
      path: /actuator/prometheus
      targetPort: 8080
      basicAuth:
        password:
          name: idgenerator-lt-spring
          key: password
        username:
          name: idgenerator-lt-spring
          key: user
  namespaceSelector:
    matchNames:
      - idgenerator-lt
  selector:
    matchLabels:
      app.kubernetes.io/name: idgenerator-lt
