INSERT INTO ID_INCREMENT (ID, BATCH, GENERATOR_CODE, INCREMENT_VALUE) VALUES (3, 2000, 'ordAddrId', 1000);
INSERT INTO ID_INCREMENT (ID, BATCH, GENERATOR_CODE, INCREMENT_VALUE) VALUES (1, 500,  'order_code', 8500);
INSERT INTO ID_INCREMENT (ID, BATCH, GENERATOR_CODE, INCREMENT_VALUE) VALUES (2, 1000, 'eliteIdSession', 5000);
INSERT INTO ID_INCREMENT (ID, BATCH, GENERATOR_CODE, INCREMENT_VALUE) VALUES (4, 1500, 'ordLId', 11500);
